/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;

/**
 *
 * @author bcarr
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        funcionarioMenu = new javax.swing.JMenu();
        novoFuncionarioMenuItem = new javax.swing.JMenuItem();
        buscarFuncionarioMenuItem = new javax.swing.JMenuItem();
        salarioMenu = new javax.swing.JMenu();
        calcularSalarioMenuItem = new javax.swing.JMenuItem();
        ferramentasMenu = new javax.swing.JMenu();
        sairMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Gestão de Funcionários");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jLabel1)
                .addContainerGap(142, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jLabel1)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        funcionarioMenu.setText("Funcionário");
        funcionarioMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funcionarioMenuActionPerformed(evt);
            }
        });

        novoFuncionarioMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        novoFuncionarioMenuItem.setText("Novo Funcionário");
        novoFuncionarioMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoFuncionarioMenuItemActionPerformed(evt);
            }
        });
        funcionarioMenu.add(novoFuncionarioMenuItem);

        buscarFuncionarioMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        buscarFuncionarioMenuItem.setText("Buscar Funcionário");
        funcionarioMenu.add(buscarFuncionarioMenuItem);

        jMenuBar1.add(funcionarioMenu);

        salarioMenu.setText("Salário");

        calcularSalarioMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        calcularSalarioMenuItem.setText("Calcular Salário");
        calcularSalarioMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularSalarioMenuItemActionPerformed(evt);
            }
        });
        salarioMenu.add(calcularSalarioMenuItem);

        jMenuBar1.add(salarioMenu);

        ferramentasMenu.setText("Ferramentas");
        ferramentasMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ferramentasMenuActionPerformed(evt);
            }
        });

        sairMenuItem.setText("Sair");
        sairMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairMenuItemActionPerformed(evt);
            }
        });
        ferramentasMenu.add(sairMenuItem);

        jMenuBar1.add(ferramentasMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void funcionarioMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funcionarioMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_funcionarioMenuActionPerformed

    private void novoFuncionarioMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoFuncionarioMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_novoFuncionarioMenuItemActionPerformed

    private void ferramentasMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ferramentasMenuActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ferramentasMenuActionPerformed

    private void sairMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairMenuItemActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_sairMenuItemActionPerformed

    private void calcularSalarioMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularSalarioMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calcularSalarioMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    public JMenuItem getBuscarFuncionarioMenuItem() {
        return buscarFuncionarioMenuItem;
    }

    public JMenuItem getCalcularSalarioMenuItem() {
        return calcularSalarioMenuItem;
    }

    public JMenu getFerramentasMenu() {
        return ferramentasMenu;
    }

    public JMenu getFuncionarioMenu() {
        return funcionarioMenu;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public JMenuItem getNovoFuncionarioMenuItem() {
        return novoFuncionarioMenuItem;
    }

    public JMenuItem getSairMenuItem() {
        return sairMenuItem;
    }

    public JMenu getSalarioMenu() {
        return salarioMenu;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem buscarFuncionarioMenuItem;
    private javax.swing.JMenuItem calcularSalarioMenuItem;
    private javax.swing.JMenu ferramentasMenu;
    private javax.swing.JMenu funcionarioMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem novoFuncionarioMenuItem;
    private javax.swing.JMenuItem sairMenuItem;
    private javax.swing.JMenu salarioMenu;
    // End of variables declaration//GEN-END:variables
}
